spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/kisandisha
    username: postgres
    password: hinash

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true